<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Testing.NUnit" Version="15.0.0--ci.6" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CK.Testing.StObjEngine" Version="33.0.0--ci.16" />
    <PackageReference Include="CK.Testing.AspNetServer.Auth" Version="30.0.0--ci.14" />
    <PackageReference Include="CK.AppIdentity.Hosting" Version="0.14.0--ci.9" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CK.Cris.Executor.Engine" Version="0.43.0--ci.9" />
    <PackageReference Include="CK.Cris.HttpSender" Version="0.43.0--ci.9" />
    <!-- This project tests Basic login and DelayedCommand. -->
    <PackageReference Include="CK.Cris.Auth" Version="0.43.0--ci.9" />
    <PackageReference Include="CK.Cris.DelayedCommand" Version="0.43.0--ci.9" />
    <ProjectReference Include="../../CK.Cris.AspNet.Auth.Basic/CK.Cris.AspNet.Auth.Basic.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.Cris.AspNet.Engine\CK.Cris.AspNet.Engine.csproj" />
  </ItemGroup>
</Project>