<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Testing.NUnit" Version="15.0.5--ci.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CK.Testing.StObjEngine" Version="33.1.0--ci.8" />
    <PackageReference Include="CK.Testing.AspNetServer.Auth" Version="30.1.0--ci.6" />
    <PackageReference Include="CK.AppIdentity.Hosting" Version="0.14.5--ci.6" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CK.Cris.Executor.Engine" Version="0.44.0--ci.6" />
    <PackageReference Include="CK.Cris.HttpSender" Version="0.44.0--ci.6" />
    <!-- This project tests Basic login and DelayedCommand. -->
    <PackageReference Include="CK.Cris.Auth" Version="0.44.0--ci.6" />
    <PackageReference Include="CK.Cris.DelayedCommand" Version="0.44.0--ci.6" />
    <ProjectReference Include="../../CK.Cris.AspNet.Auth.Basic/CK.Cris.AspNet.Auth.Basic.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.Cris.AspNet.Engine\CK.Cris.AspNet.Engine.csproj" />
  </ItemGroup>
</Project>